USE [master]
GO

/****** Object:  Database [DB_yyyu]    Script Date: 2017/11/21 17:51:10 ******/
CREATE DATABASE [DB_yyyu]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_yyyu', FILENAME = N'E:\SQL\DB_yyyu.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_yyyu_log', FILENAME = N'E:\SQL\DB_yyyu_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_yyyu] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_yyyu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_yyyu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_yyyu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_yyyu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_yyyu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_yyyu] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_yyyu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_yyyu] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DB_yyyu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_yyyu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_yyyu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_yyyu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_yyyu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_yyyu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_yyyu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_yyyu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_yyyu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_yyyu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_yyyu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_yyyu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_yyyu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_yyyu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_yyyu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_yyyu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_yyyu] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_yyyu] SET  MULTI_USER 
GO

ALTER DATABASE [DB_yyyu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_yyyu] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_yyyu] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_yyyu] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_yyyu] SET  READ_WRITE 
GO

